#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-base64url
Version  : 1.4
Release  : 15
URL      : https://cran.r-project.org/src/contrib/base64url_1.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/base64url_1.4.tar.gz
Summary  : Fast and URL-Safe Base64 Encoder and Decoder
Group    : Development/Tools
License  : GPL-3.0
Requires: R-base64url-lib = %{version}-%{release}
Requires: R-backports
BuildRequires : R-backports
BuildRequires : R-base64enc
BuildRequires : R-checkmate
BuildRequires : R-openssl
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
"-", the 63rd character ("/") is replaced with "_". Furthermore, the encoder
    does not fill the string with trailing "=". The resulting encoded strings
    comply to the regular expression pattern "[A-Za-z0-9_-]" and thus are
    safe to use in URLs or for file names.
    The package also comes with a simple base32 encoder/decoder suited for
    case insensitive file systems.

%package lib
Summary: lib components for the R-base64url package.
Group: Libraries

%description lib
lib components for the R-base64url package.


%prep
%setup -q -n base64url
pushd ..
cp -a base64url buildavx2
popd
pushd ..
cp -a base64url buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737132652

%install
export SOURCE_DATE_EPOCH=1737132652
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/base64url/DESCRIPTION
/usr/lib64/R/library/base64url/INDEX
/usr/lib64/R/library/base64url/Meta/Rd.rds
/usr/lib64/R/library/base64url/Meta/features.rds
/usr/lib64/R/library/base64url/Meta/hsearch.rds
/usr/lib64/R/library/base64url/Meta/links.rds
/usr/lib64/R/library/base64url/Meta/nsInfo.rds
/usr/lib64/R/library/base64url/Meta/package.rds
/usr/lib64/R/library/base64url/Meta/vignette.rds
/usr/lib64/R/library/base64url/NAMESPACE
/usr/lib64/R/library/base64url/NEWS.md
/usr/lib64/R/library/base64url/R/base64url
/usr/lib64/R/library/base64url/R/base64url.rdb
/usr/lib64/R/library/base64url/R/base64url.rdx
/usr/lib64/R/library/base64url/doc/Benchmarks.R
/usr/lib64/R/library/base64url/doc/Benchmarks.Rmd
/usr/lib64/R/library/base64url/doc/Benchmarks.html
/usr/lib64/R/library/base64url/doc/index.html
/usr/lib64/R/library/base64url/help/AnIndex
/usr/lib64/R/library/base64url/help/aliases.rds
/usr/lib64/R/library/base64url/help/base64url.rdb
/usr/lib64/R/library/base64url/help/base64url.rdx
/usr/lib64/R/library/base64url/help/paths.rds
/usr/lib64/R/library/base64url/html/00Index.html
/usr/lib64/R/library/base64url/html/R.css
/usr/lib64/R/library/base64url/tests/testthat.R
/usr/lib64/R/library/base64url/tests/testthat/helper.R
/usr/lib64/R/library/base64url/tests/testthat/test_base32.R
/usr/lib64/R/library/base64url/tests/testthat/test_base64.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/base64url/libs/base64url.so
/V4/usr/lib64/R/library/base64url/libs/base64url.so
/usr/lib64/R/library/base64url/libs/base64url.so
